import{a as q,S as B,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const E="https://pixabay.com/api/",P="50372154-a6db83142fe95720537b26d91";async function p(o,t,i){try{return(await q.get(E,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i}})).data}catch(s){throw s}}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-btn"),$=new B(".gallery a");function b(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:a,comments:v,downloads:S})=>`<li class="photo-card">
          <a href="${s}">
            <img src="${i}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b><br>${r}</p>
            <p class="info-item"><b>Views</b><br>${a}</p>
            <p class="info-item"><b>Comments</b><br>${v}</p>
            <p class="info-item"><b>Downloads</b><br>${S}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){h.innerHTML=""}function L(){y.classList.add("active")}function u(){y.classList.remove("active")}function w(){g.classList.add("active")}function m(){g.classList.remove("active")}const x=document.querySelector(".form"),H=document.querySelector('input[name="search-text"]'),I=document.querySelector(".load-btn");let l="",n=0;const d=15;let f=0;x.addEventListener("submit",async o=>{if(o.preventDefault(),l=H.value.trim(),!l){c.error({message:"Enter a search query!"});return}n=1,O(),m(),L();try{const t=await p(l,n,d);f=t.totalHits,setTimeout(()=>{if(u(),t.hits.length===0){c.error({id:"error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInDown"});return}b(t.hits),n*d<f&&w()},600)}catch{u(),c.error({title:"Error",message:"Something went wrong. Please try again later."})}});function M(){const o=document.querySelector(".photo-card");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}I.addEventListener("click",async()=>{n+=1,L(),m();try{const o=await p(l,n,d);setTimeout(()=>{u(),b(o.hits),M(),n*d>=f?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}),m()):w()},600)}catch{u(),c.error({title:"Error",message:"Something went wrong."})}});
//# sourceMappingURL=index.js.map
